services:
  postgres:
    image: postgres:16-alpine
    container_name: biteplate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oyatillo_200516
      POSTGRES_DB: biteplate_db
    ports:
      - "5432:5432"
    volumes:
      - biteplate_pg_data:/var/lib/postgresql/data
      - ./BitePlate-Backend/migrations/000_schema_and_seed.sql:/docker-entrypoint-initdb.d/001_schema.sql
      - ./BitePlate-Backend/migrations/001_combo_and_split.sql:/docker-entrypoint-initdb.d/002_combo_split.sql

volumes:
  biteplate_pg_data:
